baseURL            = "https://blog.codepurist.com"
languageCode       = "en-us"
title              = "The CodePurist Blog"
paginate           = 13
theme              = "m10c"
pygmentsStyle      = "monokai"
pygmentsCodefences = true
enforce_ssl        = true
googleAnalytics  = "UA-161720451-1"

[params]
  author = "The CodePurist"
  shortname = "The CodePurist"
  headline = "News from the CodePurist"
  description = "collects interesting topics about software and coding"

  [[params.social]]
    name = "github"
    url = "https://github.com/breiting"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/codepurist"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bernhard-reitinger-8a4a0b33"
