baseURL            = "https://blog.geistreich.io"
languageCode       = "en-us"
title              = "geistreich blog"
paginate           = 13
theme              = "m10c"
pygmentsStyle      = "monokai"
pygmentsCodefences = true
enforce_ssl        = true
googleAnalytics  = "UA-161720451-1"

[params]
  author = "Bernhard Reitinger"
  headline = "Bernhard's Tech Notes"
  description = "collects interesting topics about (suckless) software"

  [[params.social]]
    name = "github"
    url = "https://github.com/breiting"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/rebreiting"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bernhard-reitinger-8a4a0b33"
