baseURL            = "https://breiting.github.io"
languageCode       = "en-us"
title              = "@breiting"
paginate           = 7
theme              = "m10c"
pygmentsStyle      = "monokai"                         # https://help.farbox.com/pygments.html
pygmentsCodefences = true
enforce_ssl        = true
# googleAnalytics  = ""                                # Enable Google Analytics https://gohugo.io/templates/internal/#google-analytics

[params]
  author = "Bernhard Reitinger"
  description = "software minimalist"

  [[params.social]]
    name = "github"
    url = "https://github.com/breiting"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/rebreiting"
